### PR TITLE
#155514841 Make the dashboard buttons clear

### PR DESCRIPTION
**Pull request by muhallan**
#### What does this PR do?
Ensures that the run and save buttons on the dashboard are clear 
#### Description of Task to be completed?
Modify the save and run buttons to be self-descriptive and easily understood.
#### How should this be manually tested?
Load the site in the browser and navigate to `/dashboard`
#### What are the relevant pivotal tracker stories?
#155514841
#### Screenshots 
Changes added are on the `Run` and `Save` buttons
image
image

### CODE REVIEW

**Review by Ashaba — COMMENTED** [review]
Would appreciate if you uploaded an image of your task in the PR as this would visually help in review.

**Review by eric-elem — COMMENTED** [review]
LGTM

**Comment by muhallan** [comment]
@Ashaba I have updated the description of the PR with the images

**Comment by Ashaba** [comment]
LGTM

**Pull request merged**
